### ISSUE TITLE
INFOGRAFÍA 

### ISSUE THREAD

**Issue by ElvisS10** [SistemasTecTlaxiaco/infografia-ElvisS10-2#2]
[Infografia-Gestion de Proyectos..pdf](https://github.com/SistemasTecTlaxiaco/infografia-ElvisS10-2/files/7125271/Infografia-Gestion.de.Proyectos.pdf)

**Comment by EDITH-R** [comment]
Calificación:20

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
